"""JSONB

Revision ID: 217b261f3cce
Revises: b4889d5aa8a2
Create Date: 2024-02-03 21:17:37.877613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217b261f3cce'
down_revision = 'b4889d5aa8a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
